[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-transaction-executor"
version = "1.8.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
log = "0.4.14"
solana-client = { path = "../client", version = "=1.8.0" }
solana-logger = { path = "../logger", version = "=1.8.0" }
solana-measure = { path = "../measure", version = "=1.8.0" }
solana-sdk = { path = "../sdk", version = "=1.8.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
